[profile.default]
ffi = true
ast = true              # Used for `test/lib/quabi`.
solc_version = "0.8.30"
optimizer = true
optimizer-runs = 200
via_ir = true
evm_version = "prague"
src = "src"
out = "out"
libs = ["dependencies"]
test = "test"
cache_path = "cache"

[profile.default.fmt]
line_length = 120
bracket_spacing = true
number_underscore = "thousands"
wrap_comments = true
int_types = "long"
quote_style = "double"
multiline_func_header = "attributes_first"
sort_imports = true

[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256

[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}"

[dependencies]
forge-std = "1.9.6"
"@openzeppelin-contracts" = "5.3.0"
olympus-v3 = { git = "https://github.com/OlympusDAO/olympus-v3.git", branch = "master", version = "3.0.0" }
solmate = "6.8.0"
